version: '3.8'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql  # Corrigido o mapeamento de volumes
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: root
    networks:
      - node-network

  node_app:
    build: 
      context: ./node_app
    container_name: node_app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: "node index.js"
    volumes:
      - ./node_app:/usr/src/app  # Corrigido o mapeamento de volumes
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "3000:3000"
    networks:
      - node-network
    depends_on:
      - db
   
  nginx:
    build: 
      context: ./nginx
    container_name: nginx
    tty: true
    ports:
      - "8080:80"
    networks:
      - node-network
    depends_on:
      - node_app
    
networks:
  node-network:
    driver: bridge