version: '3.8'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    volumes:
      - ./mysql:/var/lib/mysql  # Corrigido o mapeamento de volumes
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - node-network

  node_app:
    build: ./node_app
    container_name: node_app
    entrypoint: ["dockerize", "-wait", "tcp://db:3306", "-timeout", "20s"]
    networks:
      - node-network
    volumes:
      - ./node_app:/usr/src/app  # Corrigido o mapeamento de volumes
    tty: true
    depends_on:
      - db
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "8080:80"
    depends_on:
      - node_app

networks:
  node-network:
    driver: bridge